version: 40
jobs:
- name: test
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !ShellStep
    name: Test and Prepare Cache
    image: rust:alpine3.20
    commands: |
      # Install dependencies needed for compilation
      apk add --no-cache \
        build-base \
        openssl-dev \
        pkgconfig \
        musl-dev \
        linux-headers \
        cmake \
        perl

      # Add the musl target for cross-compilation
      rustup target add x86_64-unknown-linux-musl

      # This will download dependencies, compile, and run tests.
      # The resulting 'target' directory will be in the workspace.
      cargo test --target x86_64-unknown-linux-musl
    condition: SUCCESSFUL
  - !SetupCacheStep
    name: Cache Cargo artifacts
    # Use a key based on your lock file for smarter caching
    key: 'cargo-v1-@hash:Cargo.lock@'
    paths:
    # Cache both the compiled artifacts and the downloaded packages
    - ./target
    - /usr/local/cargo/registry
    uploadStrategy: UPLOAD_IF_CHANGED
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !SetupCacheStep
    name: Restore Cargo Cache
    # Use the same key to restore the cache
    key: 'cargo-v1-@hash:Cargo.lock@'
    paths:
    - ./target
    - /usr/local/cargo/registry
    # This strategy is correct for the downstream job
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: Docker
    output: !RegistryOutput
      tags: '@server@/@project_path@/@project_name@:latest'
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: publish_token
    # Your Dockerfile's 'release' stage will be used here
    moreOptions: --target release
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    projects: justencrypt
  jobDependencies:
  - jobName: test
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400