version: 39
jobs:
- name: build
  steps:
  - !CommandStep
    name: ls
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        ls -la
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: docker-build
    buildPath: .
    output: !RegistryOutput
      tags: latest
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
