version: 40
jobs:
- name: Test
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
  - !ShellScriptStep
    name: Run Docker Test Build
    image: docker:24.0
    commands: |
    	set -e
    	docker build --target test .
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: build
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: Docker
    output: !RegistryOutput
      tags: '@server@/@project_path@/@project_name@:latest'
    registryLogins:
    - registryUrl: '@server_url@'
      userName: '@job_token@'
      passwordSecret: publish_token
    moreOptions: --target release
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    projects: justencrypt
  jobDependencies:
  - jobName: Test
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
