[debug]
address = "0.0.0.0"
domain = { env = "ROCKET_SERVER_DOMAIN" }
port = 8000
workers = 16
keep_alive = 5
log_level = "normal"
secret_key = { env = "ROCKET_SECRET_KEY" }

[release]
address = "0.0.0.0"
domain = { env = "ROCKET_SERVER_DOMAIN" }
port = 8000
workers = 64
keep_alive = 5
log_level = "critical"
secret_key = { env = "ROCKET_SECRET_KEY" }

# [default.tls]
# certs = "cert.crt"
# key = "key.key"

[default.limits]
form = "64 GiB"
data-form = "64 GiB"
file = "64 GiB"
json = "64 GiB"
msgpack = "64 GiB"
"file/jpg" = "64 GiB"
bytes = "64 GiB"
string = "64 GiB"