[debug]
address = "0.0.0.0"
port = 8000
workers = 16
keep_alive = 5
log_level = "normal"
secret_key = { env = "ROCKET_SECRET_KEY" }

[release]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
log_level = "critical"
secret_key = { env = "ROCKET_SECRET_KEY" }

# [default.tls]
# certs = "cert.crt"
# key = "key.key"

[default.limits]
form = "10 MiB"
data-form = "10 MiB"
file = "64 GiB"
json = "10 MiB"
msgpack = "1 MiB"
"file/jpg" = "10 GiB"
bytes = "10 MiB"
string = "10 MiB"
